package ng.unilag.mediqueue.web.support;

import ng.unilag.mediqueue.model.Role;

import java.security.SecureRandom;
import java.time.Duration;
import java.time.Instant;
import java.util.Base64;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

/**
 * In-memory session registry: random token in, logged-in user out.
 *
 * <p>Sessions are intentionally not persisted. Restarting the server logs everyone out,
 * which is the correct trade for a clinic system -- appointment data must survive a
 * restart, but a stale session must not.
 *
 * <p>Spring Boot port: replaced by Spring Security's session management. The Session
 * record below is roughly its Authentication object.
 */
public final class SessionStore {

    public static final String COOKIE_NAME = "mediqueue_session";
    private static final Duration LIFETIME = Duration.ofHours(8); // one clinic day

    /** What the server remembers about a signed-in user. */
    public record Session(long userId, String fullName, Role role, Instant expiresAt) {

        public boolean isExpired() {
            return Instant.now().isAfter(expiresAt);
        }
    }

    /**
     * Cryptographically strong, unlike java.util.Random. A session token generated by a
     * predictable PRNG can be guessed by anyone who observes a few, which is session
     * hijacking with extra steps.
     */
    private final SecureRandom random = new SecureRandom();

    /** Concurrent because HttpServer dispatches requests on a thread pool. */
    private final Map<String, Session> sessions = new ConcurrentHashMap<>();

    /** Creates a session and returns its token. */
    public String create(long userId, String fullName, Role role) {
        byte[] bytes = new byte[32]; // 256 bits, far beyond brute force
        random.nextBytes(bytes);
        String token = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
        sessions.put(token, new Session(userId, fullName, role, Instant.now().plus(LIFETIME)));
        return token;
    }

    /** Looks up a live session, discarding it if it has expired. */
    public Optional<Session> lookup(String token) {
        if (token == null || token.isBlank()) {
            return Optional.empty();
        }
        Session session = sessions.get(token);
        if (session == null) {
            return Optional.empty();
        }
        if (session.isExpired()) {
            sessions.remove(token);
            return Optional.empty();
        }
        return Optional.of(session);
    }

    public void invalidate(String token) {
        if (token != null) {
            sessions.remove(token);
        }
    }

    /** Drops expired entries so the map cannot grow without bound. */
    public int purgeExpired() {
        int before = sessions.size();
        sessions.values().removeIf(Session::isExpired);
        return before - sessions.size();
    }

    public int activeCount() {
        return sessions.size();
    }

    public static int lifetimeSeconds() {
        return (int) LIFETIME.toSeconds();
    }
}
